### PR TITLE
Android library updated for headset detection

### PR DESCRIPTION
**Pull request by iamsidv**
The jar file contains the updated compile source. 
It has been tested with Unity 2019.1

### CODE REVIEW

**Comment by alamboley** [comment]
Awesome @iamsidv, would you mind to add to the README.md how you did it?

**Comment by iamsidv** [comment]
@alamboley Sure, not a problem. I will update you once the readme is done. I am now checking the iOS  version.

**Comment by iamsidv** [comment]
@alamboley are you referring to the steps I took to create a jar file? If yes, I could add the url which I followed in README.md

**Comment by alamboley** [comment]
@iamsidv yeah absolutely, I remembered created an Android Studio project for compiling the jar. Don't know if it's still the fastest way to do it!

**Comment by iamsidv** [comment]
> @iamsidv yeah absolutely, I remembered created an Android Studio project for compiling the jar. Don't know if it's still the fastest way to do it!

Apparently, that is one of the ways to do. I also followed the same steps.

**Pull request merged**
